# Site settings
title: Prioritized.net
email: derekprior@gmail.com
description: >
  The personal site of Derek Prior, an experienced developer and engineering leader.
baseurl: ""
url: "https://www.prioritized.net"
permalink: "/blog/:title"
include: [".well-known"]

# build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
